version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-data-dog-refuge-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres

  db:
    container_name: postgres_16-2_alpine_3-19
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local