CREATE SCHEMA IF NOT EXISTS refuge;

CREATE SEQUENCE IF NOT EXISTS refuge.hibernate_sequence START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS refuge.dog
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    toy  JSONB,
    CONSTRAINT pk_dog PRIMARY KEY (id)
);
